### ISSUE TITLE
Update event only fires when typing very slowly

### ISSUE THREAD

**Issue by jackmcdade** [pespantelis/vue-typeahead#3]
I tried adding `debounce` to the input template but it didn't help. Unless I type at the rate of 1 key per second, the ajax requests are basically ignored completely and nothing happens.

**Comment by pespantelis** [comment]
I have fixed it but I didn't publish it because of some issues on my pc. I just managed to publish it.

Thanks :)

**Comment by jackmcdade** [comment]
That didn't fix it. It still doesn't respond to quick typing. It also seems that the query is always one character behind what I'm typing, so if i'm searching for `blog` the query is `blo`.

**Comment by jackmcdade** [comment]
A apologize, I still had the hacked in `debounce`. It seems to be working now :) :+1:

**Comment by pespantelis** [comment]
It's ok :)

**Comment by roggel2000** [comment]
Exactly how did you manage to get debounce working? If I set it on the input element, `debounce="300"` it doesn't respond to quick typing and is always one character behind.

**Comment by pespantelis** [comment]
Hi @rogierborst!

You could try this: `@input="update | debounce 300"`
http://vuejs.org/api/#debounce

**Comment by roggel2000** [comment]
Thanks!
I figured it out myself and came back here to post my findings, only to see you already reacted 2 minutes after my question.

**Comment by KimPrince** [comment]
Hi, I just tried the debouncing using `@input="update | debounce 300"`, but webpack says its an invalid expression.  Any ideas?
